apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-server
  namespace: argo
  annotations:
    workflows.argoproj.io/rbac-rule: "'ArgoCd Admins' in groups || 'ArgoCD Admins' in groups"
    workflows.argoproj.io/rbac-rule-precedence: "10"
---
apiVersion: v1
kind: Secret
metadata:
  name: argo-server.service-account-token
  namespace: argo
  annotations:
    kubernetes.io/service-account.name: argo-server
type: kubernetes.io/service-account-token
