#!/usr/bin/env sh
set -eu

generate_configmap() {
  namespace="$1"
  output_file="$2"

  {
    printf "# Generated by scripts/generate-flyway-configmaps.sh. Do not edit by hand.\n"
    printf "apiVersion: v1\n"
    printf "kind: ConfigMap\n"
    printf "metadata:\n"
    printf "  name: flyway-sql-files\n"
    printf "  namespace: %s\n" "$namespace"
    printf "data:\n"
    for migration_file in db/migration/*.sql; do
      migration_name="${migration_file##*/}"
      printf "  %s: |\n" "$migration_name"
      sed 's/^/    /' "$migration_file"
      printf "\n"
    done
  } > "$output_file"
}

generate_configmap study-dev k8s/dev/flyway-configmap.yaml
generate_configmap study-prod k8s/prod/flyway-configmap.yaml
