apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-deployment.yaml
  - app-service.yaml
  - flyway-job.yaml
  - postgres-cluster.yaml
  - postgres-haproxy-configmap.yaml
  - postgres-haproxy-deployment.yaml
  - postgres-haproxy-service.yaml
