apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - app-deployment.yaml
  - app-service.yaml
  - flyway-job.yaml
  - postgres-statefulset.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres-headless-service.yaml
