apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: hello-copilot-postgres
spec:
  teamId: hello-copilot
  numberOfInstances: 2
  users:
    test:
      - createdb
  databases:
    hello_copilot: test
  postgresql:
    version: "16"
    parameters:
      max_connections: "100"
  patroni:
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
  additionalVolumes:
    - name: postgres-socket
      mountPath: /var/run/postgresql
      targetContainers:
        - postgres
        - pgbackrest
      volumeSource:
        emptyDir: {}
    - name: pgbackrest-config
      mountPath: /etc/pgbackrest/pgbackrest.conf
      subPath: pgbackrest.conf
      targetContainers:
        - pgbackrest
      volumeSource:
        configMap:
          name: hello-copilot-postgres-pgbackrest
    - name: pgbackrest-repo
      mountPath: /var/lib/pgbackrest
      targetContainers:
        - pgbackrest
      volumeSource:
        persistentVolumeClaim:
          claimName: hello-copilot-postgres-pgbackrest-repo
  sidecars:
    - name: pgbackrest
      image: woblerr/pgbackrest:2.58.0-alpine
      command:
        - sh
        - -c
        - "trap : TERM INT; sleep infinity & wait"
      resources:
        requests:
          cpu: 25m
          memory: 64Mi
        limits:
          cpu: 200m
          memory: 256Mi
  volume:
    size: 1Gi
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
